import { Product } from "./types";

export const products: Product[] = [
  {
    id: 1,
    image: "https://picsum.photos/100?1",
    name: "Modern Chair",
    subtitle: "Wooden Chair",
    category: "Furniture",
    price: 549,
    sold: 256,
    status: "available",
  },
  {
    id: 2,
    image: "https://picsum.photos/100?2",
    name: "Nike Shoes",
    subtitle: "Running Shoes",
    category: "Shoes",
    price: 199,
    sold: 120,
    status: "low",
  },
  {
    id: 3,
    image: "https://picsum.photos/100?3",
    name: "Apple Watch",
    subtitle: "Series 9",
    category: "Electronics",
    price: 799,
    sold: 95,
    status: "out",
  },
  {
    id: 3,
    image: "https://picsum.photos/100?3",
    name: "Apple Watch",
    subtitle: "Series 9",
    category: "Electronics",
    price: 799,
    sold: 95,
    status: "out",
  },
  {
    id: 3,
    image: "https://picsum.photos/100?3",
    name: "Apple Watch",
    subtitle: "Series 9",
    category: "Electronics",
    price: 799,
    sold: 95,
    status: "out",
  },
  {
    id: 3,
    image: "https://picsum.photos/100?3",
    name: "Apple Watch",
    subtitle: "Series 9",
    category: "Electronics",
    price: 799,
    sold: 95,
    status: "out",
  },
  {
    id: 3,
    image: "https://picsum.photos/100?3",
    name: "Apple Watch",
    subtitle: "Series 9",
    category: "Electronics",
    price: 799,
    sold: 95,
    status: "out",
  },
  {
    id: 3,
    image: "https://picsum.photos/100?3",
    name: "Apple Watch",
    subtitle: "Series 9",
    category: "Electronics",
    price: 799,
    sold: 95,
    status: "out",
  },
  
];