import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/layout/navbar";
import { Providers } from "@/lib/reactquery.provider";
import ReactQueryProvider from "@/app/providers/react-quary-provider";
import React from "react";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "bottel craft",
  description: "Generated by create next app",
   icons: {
    icon: "frontend/public/image.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <ReactQueryProvider>
          <Providers>{children}
             <Script
          src="https://checkout.razorpay.com/v1/checkout.js"
          strategy="afterInteractive"
        />
          </Providers>
          <ReactQueryDevtools initialIsOpen={false} />
        </ReactQueryProvider>
        </body>
    </html>
  );
}
